export type Locale = "en" | "vn";

export const COPY = {
  en: {
    nav: { work: "Work", services: "Services", pricing: "Pricing", contact: "Contact" },
    langSwitch: { label: "VI", href: "/vn" },
    hero: {
      eyebrow: "Systems partner — Vietnam & Southeast Asia",
      title: "Software you own.",
      titleAccent: "A partner you know.",
      sub: "We replace your pile of subscriptions and messy spreadsheets with one custom system built around how your business actually works — then stay by your side as it grows.",
      ctaPrimary: "Get a free system audit",
      ctaSecondary: "See our work",
    },
    proof: {
      eyebrow: "Proof, not promises",
      title: "We run our own business on software we built.",
      body: "TechTutor Academy — our tutoring school — runs entirely on systems we designed and built ourselves. No off-the-shelf tools, no monthly SaaS bills. That's the level of ownership we build for you.",
      products: [
        {
          key: "site",
          name: "techtutor.academy",
          tag: "Marketing site",
          body: "Bilingual site with geo-routing, booking forms and ads tracking. Every enrollment starts here.",
          stat: "4 locales · SEO-first",
          link: "https://techtutor.academy",
          linkLabel: "Visit the live site",
        },
        {
          key: "portal",
          name: "TechBash",
          tag: "Learning portal",
          body: "A gamified product our students use daily — missions, XP, AI feedback, portfolios, certificates.",
          stat: "12 tracks · AI-graded",
          link: "https://bash.techtutor.academy/preview",
          linkLabel: "Try it — no signup",
        },
        {
          key: "admin",
          name: "Admin OS",
          tag: "Operations dashboard",
          body: "Students, classes, progress and payments in one internal tool. Zero spreadsheets.",
          stat: "Replaces 4 tools",
          link: "#contact",
          linkLabel: "See it on a call",
        },
      ],
      note: "All three are live in production today — not portfolio mockups.",
      link: "Visit techtutor.academy",
    },
    beforeAfter: {
      eyebrow: "Before & after",
      title: "We lived the chaos. Then we built our way out.",
      beforeLabel: "Before",
      afterLabel: "After",
      rows: [
        {
          key: "admin",
          beforeTitle: "Running the school",
          before: [
            "CRM in Google Drive + Spreadsheets",
            "Invoices in Zoho, then designed in Canva",
            "Certificates & course reports made by hand in Canva",
            "Follow-ups typed out message by message",
          ],
          afterName: "Admin OS",
          after: "One dashboard: students, classes, invoices, certificates and reports — generated automatically, sent automatically.",
        },
        {
          key: "portal",
          beforeTitle: "Teaching students",
          before: [
            "Homework sent manually after every class",
            "Portfolio pages built one by one for each student",
            "Self-study meant emailing slides and hoping",
          ],
          afterName: "TechBash",
          after: "One portal: interactive missions with instant AI feedback, automatic portfolios, and lessons students can follow without us in the room.",
        },
      ],
      footer: "That's the transformation we build for your business.",
    },
    founder: {
      eyebrow: "Who you'll work with",
      name: "Gleb Bogachev",
      role: "Founder · also runs TechTutor Academy",
      body: "I'm not a sales team — I'm the person who will build your system. I run TechTutor Academy, a coding school in Vietnam, and every product you see above is software I built to run my own business. When we work together, you talk directly to the builder.",
      quote: "“Bảo Minh has been learning with Teacher Gleb for almost a year now. At first, my son was shy and didn't know where to start with computers. Now he confidently builds small games and even created an AI chatbot for his science project!”",
      quoteBy: "— Parent of a TechTutor student",
      stats: [
        { n: "2000+", label: "students served" },
        { n: "4K+", label: "lessons delivered" },
        { n: "90%+", label: "retention rate" },
        { n: "6+", label: "years in business" },
      ],
      statsNote: "Numbers from TechTutor Academy — the business running on our software.",
      fbLabel: "TechTutor on Facebook",
      fbHref: "https://www.facebook.com/share/1An2WsT9X5/",
    },
    problem: {
      eyebrow: "The problem",
      title: "You're renting software that doesn't fit.",
      points: [
        {
          title: "Five tools, zero fit",
          body: "A booking app, a CRM, a spreadsheet, a Zalo thread — none of them talk to each other, and none of them work the way you do.",
        },
        {
          title: "Paying forever",
          body: "Subscriptions never end. Prices go up. And if the tool shuts down or changes, your business breaks with it.",
        },
        {
          title: "Losing customers in the chaos",
          body: "Missed messages, double bookings, manual follow-ups. Operational mess quietly costs you sales every single week.",
        },
      ],
    },
    calculator: {
      eyebrow: "Do the math",
      title: "What is renting really costing you?",
      sub: "Tick the tools you pay for. We'll compare 3 years of renting against building a system you own.",
      toolsLabel: "Your current tools",
      tools: [
        { key: "crm", label: "CRM / customer management", cost: 1_200_000 },
        { key: "booking", label: "Booking & scheduling app", cost: 600_000 },
        { key: "accounting", label: "Invoicing & accounting", cost: 500_000 },
        { key: "website", label: "Website builder", cost: 400_000 },
        { key: "marketing", label: "Marketing / Zalo OA tools", cost: 700_000 },
        { key: "loyalty", label: "Loyalty / membership app", cost: 800_000 },
      ],
      otherLabel: "Other software spend (₫ per month)",
      monthlyLabel: "You're paying roughly",
      rentLabel: "Renting — 3 years",
      rentSub: "And it keeps going after that. Forever.",
      ownLabel: "Owning — build + 3 years of Partner Plan",
      ownSub: "One system, built around you. Yours from day one.",
      saveLabel: "You'd save about",
      savePositive: "— and own the system at the end, instead of a stack of expired subscriptions.",
      saveNegative: "Your stack looks lean — owning may not save you money yet. Book a free audit and we'll tell you honestly.",
      cta: "Get my exact numbers — free audit",
      note: "Estimates based on typical SME pricing in Vietnam. Your audit replaces these averages with your real numbers.",
    },
    services: {
      eyebrow: "What we do",
      title: "One system. Built for you. Owned by you.",
      items: [
        {
          step: "01",
          title: "System Audit",
          price: "Free (limited time)",
          body: "We map what you pay for, what's manual, and what breaks. You get a one-page plan: what we'd replace, what you'd save. No obligation.",
        },
        {
          step: "02",
          title: "Custom Build",
          price: "From ₫25M / $1,000",
          body: "Your own web system — bookings, payments, customer portal, internal dashboard, Zalo integration. Built in weeks, not months. Yours forever.",
        },
        {
          step: "03",
          title: "Partner Plan",
          price: "From ₫2M / $80 per month",
          body: "Optional — you own the system either way. We host it, fix it, and adjust it as your business grows. Cancel anytime and keep everything: the code, the data, the system.",
        },
      ],
    },
    process: {
      eyebrow: "How it works",
      title: "From first call to running system.",
      steps: [
        { n: "1", title: "Audit call", body: "30 minutes. We learn how your business runs and where money leaks.", highlight: false },
        { n: "2", title: "48-hour prototype", body: "Before you pay anything, we build a working slice of your system — your logo, your data, one real workflow — and you click through it yourself.", highlight: true },
        { n: "3", title: "Build", body: "Fixed price, agreed upfront. 1–3 weeks. You see progress live and give feedback as we go.", highlight: false },
        { n: "4", title: "Partner", body: "We launch, train your team, and stay on as your long-term software partner.", highlight: false },
      ],
      note: "Yes — a real prototype before any commitment. We can do this because we build fast. That speed is exactly what you're hiring.",
    },
    cta: {
      title: "Stop renting. Start owning.",
      sub: "Book a free system audit — 30 minutes, no obligation. Worst case, you leave with a clear map of your own operations.",
      button: "Book your free audit",
      email: "hello@gurrengrow.com",
      channels: [
        { label: "Zalo", href: "https://zalo.me/0931140736", display: "0931 140 736" },
        { label: "WhatsApp", href: "https://wa.me/84931140736", display: "+84 931 140 736" },
      ],
    },
    footer: {
      line: "Gurren Grow — custom software systems for Southeast Asian businesses.",
      builtBy: "From the team behind",
    },
  },
  vn: {
    nav: { work: "Dự án", services: "Dịch vụ", pricing: "Bảng giá", contact: "Liên hệ" },
    langSwitch: { label: "EN", href: "/" },
    hero: {
      eyebrow: "Đối tác hệ thống — Việt Nam & Đông Nam Á",
      title: "Phần mềm của riêng bạn.",
      titleAccent: "Đối tác bạn tin tưởng.",
      sub: "Chúng tôi thay thế hàng loạt ứng dụng thuê bao và bảng tính lộn xộn bằng một hệ thống duy nhất, xây dựng đúng theo cách doanh nghiệp bạn vận hành — và đồng hành cùng bạn khi nó phát triển.",
      ctaPrimary: "Nhận đánh giá hệ thống miễn phí",
      ctaSecondary: "Xem dự án",
    },
    proof: {
      eyebrow: "Bằng chứng, không phải lời hứa",
      title: "Chúng tôi vận hành doanh nghiệp của mình bằng phần mềm tự xây dựng.",
      body: "TechTutor Academy — trung tâm dạy lập trình của chúng tôi — vận hành hoàn toàn trên hệ thống tự thiết kế và xây dựng. Không công cụ có sẵn, không phí SaaS hàng tháng. Đó chính là mức độ sở hữu chúng tôi xây dựng cho bạn.",
      products: [
        {
          key: "site",
          name: "techtutor.academy",
          tag: "Website marketing",
          body: "Website song ngữ với định tuyến theo khu vực, form đăng ký và theo dõi quảng cáo. Mọi ghi danh đều bắt đầu từ đây.",
          stat: "4 ngôn ngữ · Chuẩn SEO",
          link: "https://techtutor.academy",
          linkLabel: "Xem website thực tế",
        },
        {
          key: "portal",
          name: "TechBash",
          tag: "Cổng học tập",
          body: "Sản phẩm gamification học viên dùng mỗi ngày — nhiệm vụ, XP, phản hồi AI, hồ sơ năng lực, chứng chỉ.",
          stat: "12 lộ trình · AI chấm bài",
          link: "https://bash.techtutor.academy/preview",
          linkLabel: "Dùng thử — không cần đăng ký",
        },
        {
          key: "admin",
          name: "Admin OS",
          tag: "Bảng điều khiển vận hành",
          body: "Học viên, lớp học, tiến độ và thanh toán trong một công cụ nội bộ. Không còn bảng tính.",
          stat: "Thay thế 4 công cụ",
          link: "#contact",
          linkLabel: "Xem trực tiếp qua cuộc gọi",
        },
      ],
      note: "Cả ba đều đang chạy thực tế — không phải mockup trưng bày.",
      link: "Xem techtutor.academy",
    },
    beforeAfter: {
      eyebrow: "Trước & sau",
      title: "Chúng tôi đã sống trong sự lộn xộn đó. Rồi tự xây lối thoát.",
      beforeLabel: "Trước",
      afterLabel: "Sau",
      rows: [
        {
          key: "admin",
          beforeTitle: "Vận hành trung tâm",
          before: [
            "CRM bằng Google Drive + bảng tính",
            "Hóa đơn trên Zoho, rồi thiết kế bằng Canva",
            "Chứng chỉ & báo cáo khóa học làm tay trên Canva",
            "Chăm sóc khách gõ từng tin nhắn một",
          ],
          afterName: "Admin OS",
          after: "Một bảng điều khiển: học viên, lớp học, hóa đơn, chứng chỉ và báo cáo — tạo tự động, gửi tự động.",
        },
        {
          key: "portal",
          beforeTitle: "Dạy học viên",
          before: [
            "Bài tập gửi tay sau mỗi buổi học",
            "Trang portfolio dựng riêng cho từng học viên",
            "Tự học nghĩa là gửi slide qua email và... hy vọng",
          ],
          afterName: "TechBash",
          after: "Một cổng học tập: nhiệm vụ tương tác với phản hồi AI tức thì, portfolio tự động, và bài học học viên tự theo được mà không cần chúng tôi ngồi cạnh.",
        },
      ],
      footer: "Đó chính là sự chuyển đổi chúng tôi xây dựng cho doanh nghiệp của bạn.",
    },
    founder: {
      eyebrow: "Người bạn sẽ làm việc cùng",
      name: "Gleb Bogachev",
      role: "Nhà sáng lập · cũng điều hành TechTutor Academy",
      body: "Tôi không phải đội sales — tôi là người trực tiếp xây hệ thống cho bạn. Tôi điều hành TechTutor Academy, một trường dạy lập trình tại Việt Nam, và mọi sản phẩm bạn thấy ở trên đều là phần mềm tôi tự xây để vận hành doanh nghiệp của mình. Khi hợp tác, bạn làm việc trực tiếp với người xây dựng.",
      quote: "“Bảo Minh học với thầy Gleb gần một năm nay. Ban đầu con trai tôi nhút nhát và không biết bắt đầu từ đâu với máy tính. Giờ con tự tin làm game nhỏ và còn tạo chatbot AI cho dự án khoa học của mình!”",
      quoteBy: "— Phụ huynh học viên TechTutor",
      stats: [
        { n: "2000+", label: "học viên" },
        { n: "4K+", label: "buổi học đã dạy" },
        { n: "90%+", label: "tỷ lệ học viên gắn bó" },
        { n: "6+", label: "năm hoạt động" },
      ],
      statsNote: "Số liệu từ TechTutor Academy — doanh nghiệp vận hành trên phần mềm của chúng tôi.",
      fbLabel: "TechTutor trên Facebook",
      fbHref: "https://www.facebook.com/share/1An2WsT9X5/",
    },
    problem: {
      eyebrow: "Vấn đề",
      title: "Bạn đang thuê phần mềm không vừa với mình.",
      points: [
        {
          title: "Năm công cụ, không cái nào vừa",
          body: "App đặt lịch, CRM, bảng tính, tin nhắn Zalo — chẳng cái nào kết nối với nhau, và chẳng cái nào hoạt động theo cách của bạn.",
        },
        {
          title: "Trả tiền mãi mãi",
          body: "Thuê bao không bao giờ kết thúc. Giá cứ tăng. Nếu công cụ đóng cửa hay thay đổi, việc kinh doanh của bạn cũng gãy theo.",
        },
        {
          title: "Mất khách trong sự lộn xộn",
          body: "Tin nhắn bị sót, trùng lịch hẹn, chăm sóc khách thủ công. Sự lộn xộn vận hành âm thầm làm bạn mất doanh thu mỗi tuần.",
        },
      ],
    },
    calculator: {
      eyebrow: "Tự tính thử",
      title: "Thuê phần mềm thật sự tốn bao nhiêu?",
      sub: "Chọn những công cụ bạn đang trả tiền. Chúng tôi so sánh 3 năm đi thuê với việc xây một hệ thống thuộc về bạn.",
      toolsLabel: "Công cụ bạn đang dùng",
      tools: [
        { key: "crm", label: "CRM / quản lý khách hàng", cost: 1_200_000 },
        { key: "booking", label: "App đặt lịch", cost: 600_000 },
        { key: "accounting", label: "Hóa đơn & kế toán", cost: 500_000 },
        { key: "website", label: "Công cụ làm website", cost: 400_000 },
        { key: "marketing", label: "Marketing / Zalo OA", cost: 700_000 },
        { key: "loyalty", label: "App tích điểm / thành viên", cost: 800_000 },
      ],
      otherLabel: "Chi phí phần mềm khác (đồng / tháng)",
      monthlyLabel: "Bạn đang trả khoảng",
      rentLabel: "Đi thuê — 3 năm",
      rentSub: "Và sau đó vẫn tiếp tục trả. Mãi mãi.",
      ownLabel: "Sở hữu — xây dựng + 3 năm Gói đồng hành",
      ownSub: "Một hệ thống xây đúng theo bạn. Thuộc về bạn từ ngày đầu.",
      saveLabel: "Bạn tiết kiệm khoảng",
      savePositive: "— và cuối cùng sở hữu cả hệ thống, thay vì một đống thuê bao hết hạn.",
      saveNegative: "Chi phí của bạn khá gọn — sở hữu có thể chưa tiết kiệm hơn. Đặt lịch đánh giá miễn phí, chúng tôi sẽ nói thẳng với bạn.",
      cta: "Nhận con số chính xác — đánh giá miễn phí",
      note: "Ước tính theo mặt bằng giá phổ biến cho doanh nghiệp nhỏ tại Việt Nam. Buổi đánh giá sẽ thay các con số trung bình này bằng số liệu thật của bạn.",
    },
    services: {
      eyebrow: "Chúng tôi làm gì",
      title: "Một hệ thống. Xây cho bạn. Thuộc về bạn.",
      items: [
        {
          step: "01",
          title: "Đánh giá hệ thống",
          price: "Miễn phí (thời gian có hạn)",
          body: "Chúng tôi rà soát bạn đang trả tiền cho gì, việc gì còn thủ công, chỗ nào hay trục trặc. Bạn nhận một bản kế hoạch 1 trang: thay gì, tiết kiệm bao nhiêu. Không ràng buộc.",
        },
        {
          step: "02",
          title: "Xây dựng riêng",
          price: "Từ 25 triệu đồng",
          body: "Hệ thống web của riêng bạn — đặt lịch, thanh toán, cổng khách hàng, bảng điều khiển nội bộ, tích hợp Zalo. Hoàn thành trong vài tuần. Thuộc về bạn mãi mãi.",
        },
        {
          step: "03",
          title: "Gói đồng hành",
          price: "Từ 2 triệu đồng / tháng",
          body: "Tùy chọn — hệ thống vẫn thuộc về bạn dù có hay không. Chúng tôi vận hành, sửa lỗi và điều chỉnh khi doanh nghiệp bạn phát triển. Dừng bất cứ lúc nào và giữ lại tất cả: mã nguồn, dữ liệu, hệ thống.",
        },
      ],
    },
    process: {
      eyebrow: "Quy trình",
      title: "Từ cuộc gọi đầu tiên đến hệ thống vận hành.",
      steps: [
        { n: "1", title: "Gọi đánh giá", body: "30 phút. Chúng tôi tìm hiểu cách bạn vận hành và chỗ nào đang thất thoát.", highlight: false },
        { n: "2", title: "Bản mẫu trong 48 giờ", body: "Trước khi bạn trả bất kỳ đồng nào, chúng tôi xây một phần hệ thống chạy thật — logo của bạn, dữ liệu của bạn, một quy trình thực tế — để bạn tự tay trải nghiệm.", highlight: true },
        { n: "3", title: "Xây dựng", body: "Giá cố định, chốt trước. 1–3 tuần. Bạn theo dõi tiến độ trực tiếp và góp ý trong suốt quá trình.", highlight: false },
        { n: "4", title: "Đồng hành", body: "Ra mắt, đào tạo đội ngũ của bạn, và ở lại làm đối tác phần mềm lâu dài.", highlight: false },
      ],
      note: "Đúng vậy — bản mẫu chạy thật trước khi bạn cam kết bất cứ điều gì. Chúng tôi làm được vì chúng tôi xây rất nhanh. Chính tốc độ đó là thứ bạn đang thuê.",
    },
    cta: {
      title: "Ngừng thuê. Bắt đầu sở hữu.",
      sub: "Đặt lịch đánh giá hệ thống miễn phí — 30 phút, không ràng buộc. Tệ nhất, bạn cũng có một bản đồ rõ ràng về vận hành của chính mình.",
      button: "Đặt lịch đánh giá miễn phí",
      email: "hello@gurrengrow.com",
      channels: [
        { label: "Zalo", href: "https://zalo.me/0931140736", display: "0931 140 736" },
        { label: "WhatsApp", href: "https://wa.me/84931140736", display: "+84 931 140 736" },
      ],
    },
    footer: {
      line: "Gurren Grow — hệ thống phần mềm riêng cho doanh nghiệp Đông Nam Á.",
      builtBy: "Từ đội ngũ đứng sau",
    },
  },
} as const;
