-- =============================================================
-- TechTutor Portal — Seed Missions
-- 30 web-dev (HTML/CSS/JS) + 30 Python missions, bilingual.
-- Run AFTER schema.sql in the Supabase SQL editor.
-- =============================================================

-- ---- TRACKS -----------------------------------------------------
insert into public.tracks (slug, title_en, title_vn, description_en, description_vn, icon, sort_order)
values
  ('web', 'Web Development', 'Phát triển Web',
   'Build real websites with HTML, CSS, and JavaScript.',
   'Xây dựng website thực tế với HTML, CSS và JavaScript.', '🌐', 1),
  ('python', 'Python', 'Python',
   'Learn the language used in AI, games, and automation.',
   'Học ngôn ngữ được dùng trong AI, game và tự động hóa.', '🐍', 2)
on conflict (slug) do nothing;

-- ---- WEB MISSIONS (30) ----------------------------------------
with t as (select id from public.tracks where slug = 'web')
insert into public.missions (track_id, slug, sort_order, language, title_en, title_vn, brief_en, brief_vn, starter_code, expected_outcome, xp_reward)
select t.id, m.slug, m.sort_order, 'html', m.title_en, m.title_vn, m.brief_en, m.brief_vn, m.starter_code, m.expected_outcome, m.xp
from t, (values
  ('web-01', 1, 'Hello, world!', 'Xin chào, thế giới!',
    'Add an <h1> that says "Hello, world!" inside the body.',
    'Thêm thẻ <h1> chứa "Xin chào, thế giới!" vào body.',
    '<!DOCTYPE html>\n<html>\n<body>\n  <!-- Write your code here -->\n</body>\n</html>',
    'Page shows a large "Hello, world!" heading.', 50),
  ('web-02', 2, 'Add a paragraph', 'Thêm đoạn văn',
    'Below your heading, add a <p> tag with a short sentence about yourself.',
    'Dưới tiêu đề, thêm thẻ <p> với một câu ngắn về bạn.',
    '<!DOCTYPE html>\n<html>\n<body>\n  <h1>Hello, world!</h1>\n</body>\n</html>',
    'Heading is followed by a paragraph.', 50),
  ('web-03', 3, 'Make a list', 'Tạo danh sách',
    'Add an unordered list (<ul>) with three of your favourite foods.',
    'Thêm danh sách không thứ tự (<ul>) với ba món ăn yêu thích.',
    '<!DOCTYPE html>\n<html>\n<body>\n  <h2>My favourite foods</h2>\n</body>\n</html>',
    'Page shows a bulleted list of three items.', 60),
  ('web-04', 4, 'Add an image', 'Thêm hình ảnh',
    'Use the <img> tag to add any image from the internet. Remember the alt attribute.',
    'Dùng thẻ <img> để thêm một hình ảnh từ internet. Nhớ thuộc tính alt.',
    '<!DOCTYPE html>\n<html>\n<body>\n  <h1>My Gallery</h1>\n</body>\n</html>',
    'An image appears on the page with an alt description.', 60),
  ('web-05', 5, 'Make a link', 'Tạo liên kết',
    'Add an <a> tag that links to https://techtutor.academy.',
    'Thêm thẻ <a> liên kết tới https://techtutor.academy.',
    '<!DOCTYPE html>\n<html>\n<body>\n  <h1>My Links</h1>\n</body>\n</html>',
    'A clickable link is visible and opens TechTutor.', 60),
  ('web-06', 6, 'Headings hierarchy', 'Cấp bậc tiêu đề',
    'Use <h1>, <h2>, and <h3> to build a mini outline for a blog post.',
    'Dùng <h1>, <h2>, và <h3> để xây dàn bài bài blog.',
    '<!DOCTYPE html>\n<html>\n<body>\n</body>\n</html>',
    'Three different heading sizes appear in order.', 60),
  ('web-07', 7, 'First CSS color', 'Màu CSS đầu tiên',
    'Add a <style> tag in <head> and make the <h1> text teal.',
    'Thêm thẻ <style> trong <head> và đổi màu <h1> sang teal.',
    '<!DOCTYPE html>\n<html>\n<head>\n  <style>\n    /* CSS here */\n  </style>\n</head>\n<body>\n  <h1>Look at me</h1>\n</body>\n</html>',
    'Heading is teal coloured.', 80),
  ('web-08', 8, 'Background color', 'Màu nền',
    'Give the body a light yellow background.',
    'Đặt nền body màu vàng nhạt.',
    '<!DOCTYPE html>\n<html>\n<head>\n  <style>\n  </style>\n</head>\n<body>\n  <h1>Sunny page</h1>\n</body>\n</html>',
    'Body background is yellow.', 80),
  ('web-09', 9, 'Font size & weight', 'Cỡ chữ và độ đậm',
    'Make all paragraphs 20px and bold.',
    'Cho tất cả đoạn văn cỡ 20px và in đậm.',
    '<!DOCTYPE html>\n<html>\n<head><style></style></head>\n<body>\n  <p>Read me carefully.</p>\n</body>\n</html>',
    'Paragraph text is large and bold.', 80),
  ('web-10', 10, 'Centered text', 'Căn giữa văn bản',
    'Center your <h1> using text-align.',
    'Căn giữa <h1> bằng text-align.',
    '<!DOCTYPE html>\n<html>\n<head><style></style></head>\n<body>\n  <h1>Center me</h1>\n</body>\n</html>',
    'Heading is centered horizontally.', 80),
  ('web-11', 11, 'A colored box', 'Một hộp màu',
    'Create a <div> 200px wide, 200px tall, with a teal background.',
    'Tạo <div> rộng 200px, cao 200px, nền teal.',
    '<!DOCTYPE html>\n<html>\n<head><style></style></head>\n<body>\n  <div class="box"></div>\n</body>\n</html>',
    'A square teal box appears.', 90),
  ('web-12', 12, 'Rounded corners', 'Bo góc',
    'Round the corners of your box by 20px.',
    'Bo góc hộp với 20px.',
    '<!DOCTYPE html>\n<html>\n<head><style>.box{width:200px;height:200px;background:#2C7A7B}</style></head>\n<body>\n  <div class="box"></div>\n</body>\n</html>',
    'The teal box has rounded corners.', 90),
  ('web-13', 13, 'Three boxes side by side', 'Ba hộp cạnh nhau',
    'Use display:flex on a container to put three boxes in a row.',
    'Dùng display:flex để ba hộp xếp hàng.',
    '<!DOCTYPE html>\n<html>\n<head><style>.box{width:100px;height:100px;background:#193b92;margin:8px}</style></head>\n<body>\n  <div class="row">\n    <div class="box"></div>\n    <div class="box"></div>\n    <div class="box"></div>\n  </div>\n</body>\n</html>',
    'Three boxes are horizontally aligned.', 100),
  ('web-14', 14, 'Hover effect', 'Hiệu ứng hover',
    'Make the box change color when the mouse hovers over it.',
    'Khi rê chuột, hộp đổi màu.',
    '<!DOCTYPE html>\n<html>\n<head><style>.box{width:200px;height:200px;background:#193b92}</style></head>\n<body>\n  <div class="box"></div>\n</body>\n</html>',
    'Box changes color on hover.', 100),
  ('web-15', 15, 'Style a button', 'Tạo kiểu nút',
    'Style a <button> with brand colors: teal background, white text, rounded.',
    'Tạo kiểu <button>: nền teal, chữ trắng, bo góc.',
    '<!DOCTYPE html>\n<html>\n<head><style></style></head>\n<body>\n  <button>Click me</button>\n</body>\n</html>',
    'Button looks like a real call-to-action.', 100),
  ('web-16', 16, 'First JavaScript alert', 'Thông báo JavaScript đầu tiên',
    'Add a <script> that shows an alert saying "Hello from JS!" when the page loads.',
    'Thêm <script> hiện alert "Hello from JS!" khi tải trang.',
    '<!DOCTYPE html>\n<html>\n<body>\n  <script>\n    // your code\n  </script>\n</body>\n</html>',
    'Browser shows an alert popup.', 110),
  ('web-17', 17, 'Click a button', 'Bấm nút',
    'Make the button show an alert when clicked.',
    'Khi bấm nút, hiện alert.',
    '<!DOCTYPE html>\n<html>\n<body>\n  <button id="btn">Click me</button>\n  <script></script>\n</body>\n</html>',
    'Clicking the button triggers an alert.', 110),
  ('web-18', 18, 'Change text on click', 'Đổi chữ khi bấm',
    'When the button is clicked, change the <h1> text to "You clicked me!".',
    'Khi bấm nút, đổi <h1> thành "Bạn đã bấm tôi!".',
    '<!DOCTYPE html>\n<html>\n<body>\n  <h1 id="title">Original</h1>\n  <button id="btn">Click</button>\n  <script></script>\n</body>\n</html>',
    'Heading changes after clicking button.', 120),
  ('web-19', 19, 'Toggle a class', 'Bật/tắt class',
    'Clicking the button toggles a `dark` class on the body that changes background to black.',
    'Bấm nút bật/tắt class `dark` trên body, đổi nền sang đen.',
    '<!DOCTYPE html>\n<html>\n<head><style>.dark{background:black;color:white}</style></head>\n<body>\n  <button id="btn">Toggle dark</button>\n  <script></script>\n</body>\n</html>',
    'Background toggles between light and dark.', 120),
  ('web-20', 20, 'Counter app', 'Ứng dụng đếm',
    'Build a counter: a number and two buttons (+ / -) that change it.',
    'Tạo bộ đếm: một con số và hai nút (+ / -) để đổi.',
    '<!DOCTYPE html>\n<html>\n<body>\n  <h1 id="n">0</h1>\n  <button id="up">+</button>\n  <button id="down">-</button>\n  <script></script>\n</body>\n</html>',
    'Number goes up and down with buttons.', 130),
  ('web-21', 21, 'Read user input', 'Đọc input người dùng',
    'Add an <input>. When the user types, show the value live in a <p>.',
    'Thêm <input>. Khi gõ, hiện giá trị trực tiếp trong <p>.',
    '<!DOCTYPE html>\n<html>\n<body>\n  <input id="in" />\n  <p id="out"></p>\n  <script></script>\n</body>\n</html>',
    'Paragraph updates as user types.', 130),
  ('web-22', 22, 'Simple to-do list', 'Danh sách to-do đơn giản',
    'Type a task, click add, see it appear in a list.',
    'Gõ một việc, bấm thêm, hiện trong danh sách.',
    '<!DOCTYPE html>\n<html>\n<body>\n  <input id="task" />\n  <button id="add">Add</button>\n  <ul id="list"></ul>\n  <script></script>\n</body>\n</html>',
    'New items appear in the list after clicking add.', 140),
  ('web-23', 23, 'Random color generator', 'Trình tạo màu ngẫu nhiên',
    'Button changes the background to a random color.',
    'Nút đổi nền sang màu ngẫu nhiên.',
    '<!DOCTYPE html>\n<html>\n<body>\n  <button id="btn">Random!</button>\n  <script></script>\n</body>\n</html>',
    'Background changes color each click.', 130),
  ('web-24', 24, 'Image gallery', 'Bộ sưu tập ảnh',
    'Show 3 images in a flex row with rounded corners and shadows.',
    'Hiện 3 ảnh xếp hàng, bo góc và đổ bóng.',
    '<!DOCTYPE html>\n<html>\n<head><style></style></head>\n<body>\n  <div class="gallery"></div>\n  <script></script>\n</body>\n</html>',
    'Three styled images appear in a row.', 140),
  ('web-25', 25, 'Show / hide section', 'Hiện / ẩn phần',
    'Button toggles visibility of a hidden paragraph.',
    'Nút bật/tắt một đoạn ẩn.',
    '<!DOCTYPE html>\n<html>\n<body>\n  <button id="btn">Toggle</button>\n  <p id="msg" hidden>Surprise!</p>\n  <script></script>\n</body>\n</html>',
    'Paragraph shows and hides on click.', 130),
  ('web-26', 26, 'Form validation', 'Kiểm tra form',
    'A form with name + email; show an error if either is empty.',
    'Form gồm tên + email; báo lỗi nếu trống.',
    '<!DOCTYPE html>\n<html>\n<body>\n  <form id="f">\n    <input name="name" />\n    <input name="email" />\n    <button>Submit</button>\n  </form>\n  <p id="err" style="color:red"></p>\n  <script></script>\n</body>\n</html>',
    'Error message appears if fields empty.', 150),
  ('web-27', 27, 'Animated card', 'Thẻ có hoạt ảnh',
    'Make a card that lifts and casts a shadow on hover (use CSS transition).',
    'Thẻ nâng lên và đổ bóng khi hover (dùng CSS transition).',
    '<!DOCTYPE html>\n<html>\n<head><style></style></head>\n<body>\n  <div class="card">Hover me</div>\n</body>\n</html>',
    'Card animates smoothly on hover.', 140),
  ('web-28', 28, 'Dark mode toggle', 'Chuyển chế độ tối',
    'Real dark mode toggle that remembers choice in localStorage.',
    'Toggle dark mode thật, ghi nhớ trong localStorage.',
    '<!DOCTYPE html>\n<html>\n<body>\n  <button id="btn">Toggle</button>\n  <script></script>\n</body>\n</html>',
    'Page remembers dark mode after reload.', 160),
  ('web-29', 29, 'Stopwatch', 'Đồng hồ bấm giờ',
    'Start / stop / reset stopwatch in seconds.',
    'Start / stop / reset đồng hồ bấm giờ.',
    '<!DOCTYPE html>\n<html>\n<body>\n  <h1 id="t">0</h1>\n  <button id="start">Start</button>\n  <button id="stop">Stop</button>\n  <button id="reset">Reset</button>\n  <script></script>\n</body>\n</html>',
    'Stopwatch counts seconds and resets.', 170),
  ('web-30', 30, 'Mini portfolio page', 'Trang portfolio nhỏ',
    'Combine everything: header, about, project list, contact button. Make it pretty.',
    'Kết hợp tất cả: header, about, danh sách dự án, nút liên hệ. Trang phải đẹp.',
    '<!DOCTYPE html>\n<html>\n<head><style></style></head>\n<body>\n</body>\n</html>',
    'A polished single-page personal site.', 250)
) as m(slug, sort_order, title_en, title_vn, brief_en, brief_vn, starter_code, expected_outcome, xp)
on conflict (track_id, slug) do nothing;

-- ---- PYTHON MISSIONS (30) -------------------------------------
with t as (select id from public.tracks where slug = 'python')
insert into public.missions (track_id, slug, sort_order, language, title_en, title_vn, brief_en, brief_vn, starter_code, expected_outcome, xp_reward)
select t.id, m.slug, m.sort_order, 'python', m.title_en, m.title_vn, m.brief_en, m.brief_vn, m.starter_code, m.expected_outcome, m.xp
from t, (values
  ('py-01', 1, 'Print hello', 'In lời chào',
    'Print "Hello, world!" to the screen.',
    'In "Xin chào, thế giới!" ra màn hình.',
    '# Write your code below\n',
    'Output is exactly: Hello, world!', 50),
  ('py-02', 2, 'Variables', 'Biến',
    'Make a variable `name` with your name and print "Hi, <name>!".',
    'Tạo biến `name` chứa tên bạn, in "Xin chào, <name>!".',
    'name = ""\n# print here\n',
    'Greeting includes your name.', 50),
  ('py-03', 3, 'Math operations', 'Phép toán',
    'Calculate 25 * 4 + 7 and print the result.',
    'Tính 25 * 4 + 7 và in kết quả.',
    '# print the result here\n',
    'Output is 107.', 60),
  ('py-04', 4, 'Input from user', 'Nhập từ người dùng',
    'Ask the user for their age, then print "You are X years old".',
    'Hỏi tuổi, sau đó in "Bạn X tuổi".',
    '# use input() here\n',
    'Echoes user age back.', 60),
  ('py-05', 5, 'If/else', 'Nếu / nếu không',
    'Ask the user for a number. Print "positive" or "negative" or "zero".',
    'Hỏi một số. In "dương" hoặc "âm" hoặc "không".',
    '# your code\n',
    'Correct word for any number input.', 70),
  ('py-06', 6, 'Even or odd', 'Chẵn hay lẻ',
    'Ask for a number, say if it is even or odd.',
    'Hỏi số, cho biết chẵn hay lẻ.',
    '# your code\n',
    'Correct even/odd classification.', 70),
  ('py-07', 7, 'For loop', 'Vòng lặp for',
    'Print numbers from 1 to 10 on separate lines.',
    'In các số từ 1 đến 10 trên các dòng riêng.',
    '# your code\n',
    '10 lines, each a number.', 70),
  ('py-08', 8, 'While loop', 'Vòng lặp while',
    'Count down from 10 to 1 using a while loop.',
    'Đếm ngược từ 10 đến 1 bằng while.',
    '# your code\n',
    'Countdown printed.', 80),
  ('py-09', 9, 'Sum of a list', 'Tổng danh sách',
    'Given numbers = [3, 7, 2, 8, 5], print the sum.',
    'Cho numbers = [3, 7, 2, 8, 5], in tổng.',
    'numbers = [3, 7, 2, 8, 5]\n# print sum\n',
    'Output is 25.', 80),
  ('py-10', 10, 'Largest number', 'Số lớn nhất',
    'Find and print the largest number in a list of 5 numbers.',
    'Tìm và in số lớn nhất trong danh sách 5 số.',
    'numbers = [12, 4, 19, 8, 23]\n# your code\n',
    'Output is 23.', 80),
  ('py-11', 11, 'Function basics', 'Hàm cơ bản',
    'Write a function greet(name) that prints "Hello, name!". Call it twice.',
    'Viết hàm greet(name) in "Hello, name!". Gọi 2 lần.',
    '# define function\n# call twice\n',
    'Greets two different names.', 90),
  ('py-12', 12, 'Function that returns', 'Hàm có return',
    'Write add(a, b) that returns a+b. Print add(7, 5).',
    'Viết add(a,b) trả về a+b. In add(7,5).',
    '# your code\n',
    'Output is 12.', 90),
  ('py-13', 13, 'Strings', 'Chuỗi',
    'Take a sentence input and print it ALL UPPERCASE and reversed.',
    'Nhập một câu, in HOA hết và đảo ngược.',
    '# your code\n',
    'Uppercase + reversed string shown.', 90),
  ('py-14', 14, 'Word count', 'Đếm từ',
    'Count how many words are in a sentence the user types.',
    'Đếm số từ trong câu người dùng nhập.',
    '# your code\n',
    'Correct word count printed.', 100),
  ('py-15', 15, 'Lists & loops', 'Danh sách & vòng lặp',
    'Loop through fruits = ["apple","banana","mango"] and print each.',
    'Lặp qua fruits và in từng phần tử.',
    'fruits = ["apple","banana","mango"]\n# loop\n',
    'Each fruit on its own line.', 90),
  ('py-16', 16, 'Multiplication table', 'Bảng cửu chương',
    'Ask for a number n. Print n × 1 through n × 10.',
    'Hỏi số n. In n × 1 tới n × 10.',
    '# your code\n',
    'Full multiplication table printed.', 110),
  ('py-17', 17, 'Guessing game', 'Trò chơi đoán số',
    'Pick a secret number 1-10. Let the user guess until correct.',
    'Chọn số bí mật 1-10. Cho người dùng đoán tới khi đúng.',
    'import random\nsecret = random.randint(1, 10)\n# game loop\n',
    'Game ends when guess matches.', 130),
  ('py-18', 18, 'Dictionary basics', 'Dictionary cơ bản',
    'Make a dict of 3 students with their scores. Print each name and score.',
    'Tạo dict gồm 3 học sinh và điểm. In tên và điểm.',
    'scores = {"An": 88, "Linh": 92, "Minh": 75}\n# loop\n',
    'Each student/score printed.', 100),
  ('py-19', 19, 'Average score', 'Điểm trung bình',
    'Calculate the average of 5 numbers entered by the user.',
    'Tính trung bình 5 số người dùng nhập.',
    '# your code\n',
    'Correct average printed.', 110),
  ('py-20', 20, 'FizzBuzz', 'FizzBuzz',
    'For numbers 1-30: "Fizz" if /3, "Buzz" if /5, "FizzBuzz" if both, else the number.',
    'Với 1-30: "Fizz" nếu /3, "Buzz" nếu /5, "FizzBuzz" nếu cả hai, ngược lại in số.',
    '# your code\n',
    'Correct FizzBuzz output 1-30.', 130),
  ('py-21', 21, 'Palindrome check', 'Kiểm tra palindrome',
    'Ask for a word, say if it is a palindrome.',
    'Hỏi một từ, cho biết có phải palindrome.',
    '# your code\n',
    'Correct palindrome answer.', 120),
  ('py-22', 22, 'Password strength', 'Độ mạnh mật khẩu',
    'Ask for a password. Tell the user if it is weak (<6), medium (6-10), or strong (>10).',
    'Hỏi mật khẩu. Cho biết yếu, trung bình hay mạnh.',
    '# your code\n',
    'Strength label printed correctly.', 120),
  ('py-23', 23, 'List filter', 'Lọc danh sách',
    'From [4,7,1,9,3,12,6] print only even numbers.',
    'Từ [4,7,1,9,3,12,6] in chỉ số chẵn.',
    'nums = [4,7,1,9,3,12,6]\n# your code\n',
    'Even numbers printed.', 100),
  ('py-24', 24, 'Sort a list', 'Sắp xếp danh sách',
    'Sort a list of names alphabetically and print them.',
    'Sắp xếp danh sách tên theo bảng chữ cái.',
    'names = ["Minh","An","Bao","Linh"]\n# your code\n',
    'Sorted names printed.', 100),
  ('py-25', 25, 'Tip calculator', 'Tính tiền tip',
    'Ask for bill total and tip %, print the tip amount and total.',
    'Hỏi tổng hóa đơn và % tip, in tip và tổng.',
    '# your code\n',
    'Correct tip + total.', 130),
  ('py-26', 26, 'Number guessing v2', 'Đoán số v2',
    'Like the guessing game but only allow 5 attempts.',
    'Như trò đoán số nhưng giới hạn 5 lần.',
    'import random\n# your code\n',
    'Game ends after 5 wrong guesses.', 150),
  ('py-27', 27, 'Word reverser', 'Đảo từ',
    'Ask for a sentence; print the words in reverse order.',
    'Hỏi một câu; in các từ theo thứ tự ngược.',
    '# your code\n',
    'Words reversed correctly.', 130),
  ('py-28', 28, 'Count vowels', 'Đếm nguyên âm',
    'Count vowels in a sentence the user enters.',
    'Đếm nguyên âm trong câu người dùng nhập.',
    '# your code\n',
    'Vowel count correct.', 130),
  ('py-29', 29, 'Mini quiz', 'Câu đố mini',
    'Ask 3 multiple-choice questions, count correct answers, print the score.',
    'Hỏi 3 câu trắc nghiệm, đếm đúng, in điểm.',
    '# your code\n',
    'Score printed at end.', 170),
  ('py-30', 30, 'Tic-tac-toe (text)', 'Caro chữ',
    'Build a text-based 3x3 tic-tac-toe for two players.',
    'Xây caro 3x3 dạng văn bản cho hai người.',
    '# your code\n',
    'Two players can play and win.', 250)
) as m(slug, sort_order, title_en, title_vn, brief_en, brief_vn, starter_code, expected_outcome, xp)
on conflict (track_id, slug) do nothing;
